trigger:
  batch: true
  branches:
    include:
      - release   # Only run pipeline when changes land in release branch
    exclude:
      - main

pr: none        # disables PR validation pipeline runs

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Install dependencies and build
  - script: |
      cd azure-demo   # go inside your React app folder
      npm install     # use install unless you have package-lock.json
      npm run build
      ls -la build
    displayName: 'Build React app'

  # Publish build output as artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'azure-demo/build'   # correct path to build folder
      artifactName: 'react-build'
      publishLocation: 'Container'