trigger:
  branches:
    include:
      - release   # Only run pipeline when changes land in release branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  # Install dependencies and build
  - script: |
      cd react-app   # 👈 go inside your React app folder
      npm ci         # clean install dependencies
      npm run build
      ls -la build
    displayName: 'Build React app'

  # Publish build output as artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'react-app/build'   # 👈 relative to repo root
      artifactName: 'react-build'
      publishLocation: 'Container'
