trigger:
  branches:
    include:
      - release   # Only run pipeline when changes land in release branch

pool:
  vmImage: 'ubuntu-latest'

stages:
# -------- CI (Build) --------
- stage: Build
  displayName: "Build React App"
  jobs:
  - job: BuildJob
    steps:
      # Install Node.js
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      # Install dependencies and build
      - script: |
          npm install
          npm run build
          ls -la build
        displayName: 'Build React app'

      # Publish build output as artifact
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'build'
          artifactName: 'react-build'
          publishLocation: 'Container'

# -------- CD (Deploy) --------
- stage: Deploy
  displayName: "Deploy to Azure Web App"
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    environment: 'development'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'react-build'
              downloadPath: '$(Pipeline.Workspace)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'tool-conn'
              appName: 'deppoc'
              package: '$(Pipeline.Workspace)/react-build/build'